INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (1, "A", "Socialdemokratiet");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (2, "B", "Radikale Venstre");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (3, "C", "Det Konservative Folkeparti");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (4, "D", "Nye Borgerlige");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (5, "F", "SF - Socialistisk Folkeparti");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (6, "H", "Forenet Frederikssund");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (7, "N", "Fjordlandslisten");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (8, "O", "Dansk Folkeparti");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (9, "P", "Anja Bisp Pedersen");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (10, "V", "Venstre, Danmarks Liberale Parti");
INSERT INTO `party` (`party_id`, `party_letter`, `party_name`) VALUES (11, "Ø", "Enhedslisten - De Rød-Grønne");